# Generated by Django 5.0 on 2024-01-14 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_email', models.EmailField(max_length=100, verbose_name='Company Email')),
                ('company_phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$', 'Only valid Phone Number is required')], verbose_name='Company Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('license', models.FileField(help_text='Accepted formats: png, jpg, jpeg , pdf. Max file size 10 MB', upload_to='client/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='License')),
                ('focal_person_name', models.CharField(max_length=100, verbose_name='Focal Person Name')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$', 'Only valid Phone Number is required')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
