# Generated by Django 5.0 on 2024-01-14 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank='', help_text='Accepted formats: png, jpg, jpeg. Max file size 10 MB', upload_to='Vehicle Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Vehicle Images'),
        ),
    ]
