# Generated by Django 5.0 on 2024-01-15 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('', 'Select Fuel Type'), ('Diesel / Nafta', 'Diesel / Nafta'), ('Benzene / Benzil', 'Benzene / Benzil')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.FileField(blank=True, help_text='Accepted formats: png, jpg, jpeg. Max file size 10 MB', upload_to='Vehicle Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Vehicle Images'),
        ),
    ]
