# Generated by Django 5.0 on 2024-01-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicledata_fuel_type_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehiclebrand', verbose_name='Vehicle Make'),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehiclecolor', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehiclemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehicletype', verbose_name='Vehicle Type'),
        ),
    ]
