# Generated by Django 4.2 on 2024-01-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicledata_is_expired_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='address',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
    ]
