# Generated by Django 4.2 on 2024-01-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='plate_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Plate Number'),
        ),
    ]
