# Generated by Django 4.2 on 2024-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_vehicledata_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('', 'Select Fuel Type'), ('Diesel / ናፍጣ', 'Diesel / ናፍጣ'), ('Benzene / ቤንዚል', 'Benzene / ቤንዚል')], max_length=50, null=True),
        ),
    ]
