# Generated by Django 4.2 on 2024-02-03 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_vehicledata_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.FileField(help_text='Accepted formats: png, jpg, jpeg', upload_to='vehicle_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Vehicle Image'),
        ),
    ]
