# Generated by Django 4.2 on 2024-02-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_areaofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='area_of_interests',
            field=models.ManyToManyField(blank=True, related_name='vehicle', to='vehicle.areaofinterest'),
        ),
    ]
