# Generated by Django 4.2 on 2024-02-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0016_vehicledata_area_of_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
