# Generated by Django 5.0 on 2024-01-14 07:09

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100, verbose_name='Pick Up Location')),
                ('drop_off', models.CharField(max_length=100, verbose_name='Drop Off Location')),
                ('daily_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily Price')),
                ('no_of_vehicles', models.IntegerField(default=1, verbose_name='Number Of Vehicles')),
                ('assigned_vehicles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned Vehicles')),
                ('production_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2024, message='Production year cannot be in the future.')], verbose_name='Production Year')),
                ('start_date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today, message="Start Date can't be before today")], verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today, message="End Date can't be before today ")], verbose_name='End Date')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 day')])),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclebrand', verbose_name='Make')),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Info')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclemodel', verbose_name='Model')),
                ('vehicle_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicletype', verbose_name='Vehicle Type')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='vehicle.vehicledata')),
                ('vehicle_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='booking.vehiclebooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
