# Generated by Django 4.2 on 2024-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_vehiclebooking_assigned_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='Remark if any'),
        ),
    ]
