# Generated by Django 4.2 on 2024-02-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.IntegerField(default=0),
        ),
    ]
