# Generated by Django 4.2 on 2024-02-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_notification_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.IntegerField(default=12),
        ),
    ]
